# IBM Data Science Specialization 

## `This notebook will contain all the code required to complete the Capstone`

### WEEK 1

In [1]:
# Importing Libraries

import pandas as pd
import numpy as np

In [2]:
print('Hello Capstone Project Course!')

Hello Capstone Project Course!

### WEEK 3

### Peer-graded Assignment: Segmenting and Clustering Neighborhoods in Toronto

####  Importing the required libraries

In [3]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
import geocoder
import requests

import folium
import matplotlib.cm as cm
import matplotlib.colors as colors

#### `Question 1`

##### 1.1) Creating a dataframe containing the Postal Code, Borough & Neighborhood raw data for the city of Toronto from Wikipedia

In [4]:
toronto_raw_df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]

##### 1.2) Showing the first 5 rows of the raw data

In [5]:
toronto_raw_df.head()

,0,1,2,3,4,5,6,7,8
0,M1ANot assigned,M2ANot assigned,M3ANorth York(Parkwoods),M4ANorth York(Victoria Village),M5ADowntown Toronto(Regent Park / Harbourfront),M6ANorth York(Lawrence Manor / Lawrence Heights),M7AQueen's Park(Ontario Provincial Government),M8ANot assigned,M9AEtobicoke(Islington Avenue)
1,M1BScarborough(Malvern / Rouge),M2BNot assigned,M3BNorth York(Don Mills)North,M4BEast York(Parkview Hill / Woodbine Gardens),"M5BDowntown Toronto(Garden District, Ryerson)",M6BNorth York(Glencairn),M7BNot assigned,M8BNot assigned,M9BEtobicoke(West Deane Park / Princess Garden...
2,M1CScarborough(Rouge Hill / Port Union / Highl...,M2CNot assigned,M3CNorth York(Don Mills)South(Flemingdon Park),M4CEast York(Woodbine Heights),M5CDowntown Toronto(St. James Town),M6CYork(Humewood-Cedarvale),M7CNot assigned,M8CNot assigned,M9CEtobicoke(Eringate / Bloordale Gardens / Ol...
3,M1EScarborough(Guildwood / Morningside / West ...,M2ENot assigned,M3ENot assigned,M4EEast Toronto(The Beaches),M5EDowntown Toronto(Berczy Park),M6EYork(Caledonia-Fairbanks),M7ENot assigned,M8ENot assigned,M9ENot assigned
4,M1GScarborough(Woburn),M2GNot assigned,M3GNot assigned,M4GEast York(Leaside),M5GDowntown Toronto(Central Bay Street),M6GDowntown Toronto(Christie),M7GNot assigned,M8GNot assigned,M9GNot assigned

##### 1.3) Converting the raw data into usable data

In [6]:
temp_list = []
# j is used for selecting the column in toronto_raw_df
for j in range(0 , 9):
    # i is used for selecting the row in toronto_raw_df
    for i in range(len(toronto_raw_df)):
        temp_var = toronto_raw_df[j][i]
        # Some cells in toronto_raw_df does not have any information. Such cells are ignored.
        
        if temp_var[3:] == 'Not assigned':
            continue
        else:
            temp_var = temp_var.replace(')' , '')
            
            if temp_var.count('(') > 1:
            # Some cells contain multiple boroughs with different neighborhood. For such exceptions, it is easier
            # to add the cell information manually later and ignoring it in this loop.
                print(temp_var)
                continue
            else:
                # The cell contains information like this - 'postalcodeborough(neighborhood/neighborhood)'
                postal_code = temp_var[:3]
                borough = temp_var[3:].split('(')[0]
                neighborhood = temp_var[3:].split('(')[1].replace('/' , ',')
                temp_list.append([postal_code , borough , neighborhood])

M3CNorth York(Don MillsSouth(Flemingdon Park
M3KNorth York(DownsviewEast (CFB Toronto

In [7]:
toronto_df = pd.DataFrame(data = temp_list, columns = ['Postal Code', 'Borough', 'Neighborhood'])
exception_list = [['M3C', 'North York', 'Don Mills , Flemingdon Park'],
                 ['M3K', 'North York', 'Downsview , CFB Toronto']]
exception_df = pd.DataFrame(data = exception_list, columns = ['Postal Code', 'Borough', 'Neighborhood'])

toronto_df = pd.concat([toronto_df , exception_df])
toronto_df.reset_index(inplace = True)
toronto_df.drop(columns = ['index'], inplace = True)

# Replacing some borough names with standardized names
toronto_df['Borough'].replace({'Downtown TorontoStn A PO Boxes25 The Esplanade':'Downtown Toronto Stn A',
                                             'East TorontoBusiness reply mail Processing Centre969 Eastern':'East Toronto Business',
                                             'EtobicokeNorthwest':'Etobicoke Northwest','East YorkEast Toronto':'East York/East Toronto',
                                             'MississaugaCanada Post Gateway Processing Centre':'Mississauga'},
                             inplace = True)

##### 1.4) Showing the usable data

In [8]:
toronto_df

,Postal Code,Borough,Neighborhood
0,M1B,Scarborough,"Malvern , Rouge"
1,M1C,Scarborough,"Rouge Hill , Port Union , Highland Creek"
2,M1E,Scarborough,"Guildwood , Morningside , West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
...,...,...,...
98,M9R,Etobicoke,"Kingsview Village , St. Phillips , Martin Grov..."
99,M9V,Etobicoke,"South Steeles , Silverstone , Humbergate , Jam..."
100,M9W,Etobicoke Northwest,"Clairville , Humberwood , Woodbine Downs , Wes..."
101,M3C,North York,"Don Mills , Flemingdon Park"
102,M3K,North York,"Downsview , CFB Toronto"

#### `Question 2`

##### 2.1) Finding the Latitude & Longitude for each postal code

DUE TO PROBLEMS WITH GEOCODER, LATITUDE & LONGITUDE CANNOT BE EXTRACTED USING GEOCODER. THEREFORE, THE LATITUDE & LONGITUDE WILL BE EXTRACTED FROM THE FILES PROVIDED BY THE COURSE

In [9]:
#coords = None

#for i in range(len(toronto_df)):
#    postal_code = toronto_df['Postal Code'][i]
#    while (coords is None):
#        g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
#        coords = g.latlng

#    toronto_df.loc[i , 'Latitude'] = coords[0]
#    toronto_df.loc[i , 'Longitude'] = coords[1]

##### 2.1.1) Finding the Latitude & Longitude for each postal code using the file

In [10]:
lat_long_coords = pd.read_csv('C:\\Users\\VISHAKMADHWARAJKADAM\\Coursera_Capstone\\Coursera_Capstone\\Geospatial_Coordinates.csv')

In [11]:
lat_long_coords.set_index(['Postal Code'], inplace = True)
lat_long_coords

              Latitude  Longitude
Postal Code
M1B          43.806686 -79.194353
M1C          43.784535 -79.160497
M1E          43.763573 -79.188711
M1G          43.770992 -79.216917
M1H          43.773136 -79.239476
...                ...        ...
M9N          43.706876 -79.518188
M9P          43.696319 -79.532242
M9R          43.688905 -79.554724
M9V          43.739416 -79.588437
M9W          43.706748 -79.594054

[103 rows x 2 columns]

In [12]:
toronto_df.set_index(['Postal Code'], inplace = True)
toronto_df

,Borough,Neighborhood
Postal Code,,
M1B,Scarborough,"Malvern , Rouge"
M1C,Scarborough,"Rouge Hill , Port Union , Highland Creek"
M1E,Scarborough,"Guildwood , Morningside , West Hill"
M1G,Scarborough,Woburn
M1H,Scarborough,Cedarbrae
...,...,...
M9R,Etobicoke,"Kingsview Village , St. Phillips , Martin Grov..."
M9V,Etobicoke,"South Steeles , Silverstone , Humbergate , Jam..."
M9W,Etobicoke Northwest,"Clairville , Humberwood , Woodbine Downs , Wes..."
M3C,North York,"Don Mills , Flemingdon Park"
M3K,North York,"Downsview , CFB Toronto"

##### 2.2) Showing the data

In [13]:
toronto_df_final = pd.concat([toronto_df , lat_long_coords], axis = 1)
toronto_df_final.head()

,Borough,Neighborhood,Latitude,Longitude
Postal Code,,,,
M1B,Scarborough,"Malvern , Rouge",43.806686,-79.194353
M1C,Scarborough,"Rouge Hill , Port Union , Highland Creek",43.784535,-79.160497
M1E,Scarborough,"Guildwood , Morningside , West Hill",43.763573,-79.188711
M1G,Scarborough,Woburn,43.770992,-79.216917
M1H,Scarborough,Cedarbrae,43.773136,-79.239476

#### `Question 3`

##### 3.1) Extracting data related to the borough 'North York'

In [50]:
north_york_df = toronto_df_final[toronto_df_final['Borough'] == 'North York']
north_york_df

,Borough,Neighborhood,Latitude,Longitude
Postal Code,,,,
M2H,North York,Hillcrest Village,43.803762,-79.363452
M2J,North York,"Fairview , Henry Farm , Oriole",43.778517,-79.346556
M2K,North York,Bayview Village,43.786947,-79.385975
M2L,North York,"York Mills , Silver Hills",43.757490,-79.374714
M2M,North York,"Willowdale , Newtonbrook",43.789053,-79.408493
M2N,North York,WillowdaleSouth,43.770120,-79.408493
M2P,North York,York Mills West,43.752758,-79.400049
M2R,North York,WillowdaleWest,43.782736,-79.442259
M3A,North York,Parkwoods,43.753259,-79.329656
M3B,North York,Don MillsNorth,43.745906,-79.352188
M3H,North York,"Bathurst Manor , Wilson Heights , Downsview North",43.754328,-79.442259
M3J,North York,"Northwood Park , York University",43.767980,-79.487262
M3L,North York,DownsviewWest,43.739015,-79.506944
M3M,North York,DownsviewCentral,43.728496,-79.495697
M3N,North York,DownsviewNorthwest,43.761631,-79.520999
M4A,North York,Victoria Village,43.725882,-79.315572
M5M,North York,"Bedford Park , Lawrence Manor East",43.733283,-79.419750
M6A,North York,"Lawrence Manor , Lawrence Heights",43.718518,-79.464763
M6B,North York,Glencairn,43.709577,-79.445073
M6L,North York,"North Park , Maple Leaf Park , Upwood Park",43.713756,-79.490074
M9L,North York,Humber Summit,43.756303,-79.565963
M9M,North York,"Humberlea , Emery",43.724766,-79.532242
M3C,North York,"Don Mills , Flemingdon Park",43.725900,-79.340923
M3K,North York,"Downsview , CFB Toronto",43.737473,-79.464763

##### 3.2) Foursquare API credentials

In [64]:
CLIENT_ID = ''
CLIENT_SECRET = ''
VERSION = '20180605'
LIMIT = 100 
ACCESS_TOKEN = ''
radius = 500

##### 3.3) Creating a function for finding top 100 venues in all neighborhoods in North York

In [16]:
def getNearbyVenues(names, latitudes, longitudes):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        #results = requests.get(url).json()
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

##### 3.4) Using the function to find the top 100 venues in North York

In [17]:
north_york_venues = getNearbyVenues(names = north_york_df['Neighborhood'],
                                   latitudes = north_york_df['Latitude'],
                                   longitudes = north_york_df['Longitude']
                                  )

Hillcrest Village
Fairview , Henry Farm , Oriole
Bayview Village
York Mills , Silver Hills
Willowdale , Newtonbrook
WillowdaleSouth
York Mills West
WillowdaleWest
Parkwoods
Don MillsNorth
Bathurst Manor , Wilson Heights , Downsview North
Northwood Park , York University
DownsviewWest
DownsviewCentral
DownsviewNorthwest
Victoria Village
Bedford Park , Lawrence Manor East
Lawrence Manor , Lawrence Heights
Glencairn
North Park , Maple Leaf Park , Upwood Park
Humber Summit
Humberlea , Emery
Don Mills , Flemingdon Park
Downsview , CFB Toronto

In [18]:
north_york_venues.head()

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Hillcrest Village,43.803762,-79.363452,New York Fries,43.803664,-79.363905,Fast Food Restaurant
1,Hillcrest Village,43.803762,-79.363452,Eagle's Nest Golf Club,43.805455,-79.364186,Golf Course
2,Hillcrest Village,43.803762,-79.363452,AY Jackson Pool,43.804515,-79.366138,Pool
3,Hillcrest Village,43.803762,-79.363452,Villa Madina,43.801685,-79.363938,Mediterranean Restaurant
4,Hillcrest Village,43.803762,-79.363452,Duncan Creek Park,43.805539,-79.360695,Dog Run

##### 3.5) Cleaning the dataset before cluster Analysis

In [46]:
north_york_onehot = pd.get_dummies(north_york_venues[['Venue Category']], prefix="", prefix_sep="")
north_york_onehot['Neighborhood'] = north_york_venues['Neighborhood']

fixed_columns = [north_york_onehot.columns[-1]] + list(north_york_onehot.columns[:-1])
north_york_onehot = north_york_onehot[fixed_columns]

north_york_grouped = north_york_onehot.groupby('Neighborhood').mean().reset_index()

north_york_grouped

,Neighborhood,Airport,American Restaurant,Art Gallery,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,Bakery,Bank,Bar,...,Spa,Sporting Goods Shop,Supermarket,Supplement Shop,Sushi Restaurant,Thai Restaurant,Toy / Game Store,Video Game Store,Vietnamese Restaurant,Women's Store
0,"Bathurst Manor , Wilson Heights , Downsview North",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.111111,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.055556,0.000000,0.000000,0.000000,0.000000,0.000000
1,Bayview Village,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.250000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,"Bedford Park , Lawrence Manor East",0.0,0.045455,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.045455,0.045455,0.000000,0.000000,0.000000,0.045455
3,"Don Mills , Flemingdon Park",0.0,0.000000,0.058824,0.000000,0.058824,0.0,0.000000,0.000000,0.000000,...,0.000000,0.058824,0.058824,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Don MillsNorth,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,"Downsview , CFB Toronto",0.5,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,DownsviewCentral,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,DownsviewNorthwest,0.0,0.000000,0.000000,0.000000,0.000000,0.2,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,DownsviewWest,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.200000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,"Fairview , Henry Farm , Oriole",0.0,0.016129,0.000000,0.000000,0.016129,0.0,0.016129,0.032258,0.016129,...,0.016129,0.016129,0.000000,0.016129,0.000000,0.000000,0.016129,0.016129,0.000000,0.016129
10,Glencairn,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.200000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000
11,Hillcrest Village,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,Humber Summit,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,"Humberlea , Emery",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,"Lawrence Manor , Lawrence Heights",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000
15,"North Park , Maple Leaf Park , Upwood Park",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.250000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,"Northwood Park , York University",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.142857,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000
17,Parkwoods,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,Victoria Village,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,"Willowdale , Newtonbrook",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,WillowdaleSouth,0.0,0.000000,0.000000,0.034483,0.000000,0.0,0.000000,0.034483,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.068966,0.000000,0.000000,0.000000,0.034483,0.000000
21,WillowdaleWest,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,York Mills West,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

##### 3.6) k-Means Clustering

In [47]:
kclusters = 5

north_york_grouped_clustering = north_york_grouped.drop('Neighborhood', 1)

kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(north_york_grouped_clustering)

labels = kmeans.labels_

In [48]:
north_york_grouped['Labels'] = labels
fixed_columns = [north_york_grouped.columns[-1]] + list(north_york_grouped.columns[:-1])
north_york_grouped = north_york_grouped[fixed_columns]
north_york_grouped

,Labels,Neighborhood,Airport,American Restaurant,Art Gallery,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,Bakery,Bank,...,Spa,Sporting Goods Shop,Supermarket,Supplement Shop,Sushi Restaurant,Thai Restaurant,Toy / Game Store,Video Game Store,Vietnamese Restaurant,Women's Store
0,2,"Bathurst Manor , Wilson Heights , Downsview North",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.111111,...,0.000000,0.000000,0.000000,0.000000,0.055556,0.000000,0.000000,0.000000,0.000000,0.000000
1,2,Bayview Village,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.250000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,"Bedford Park , Lawrence Manor East",0.0,0.045455,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.045455,0.045455,0.000000,0.000000,0.000000,0.045455
3,2,"Don Mills , Flemingdon Park",0.0,0.000000,0.058824,0.000000,0.058824,0.0,0.000000,0.000000,...,0.000000,0.058824,0.058824,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2,Don MillsNorth,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,3,"Downsview , CFB Toronto",0.5,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,2,DownsviewCentral,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,2,DownsviewNorthwest,0.0,0.000000,0.000000,0.000000,0.000000,0.2,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,2,DownsviewWest,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.200000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,2,"Fairview , Henry Farm , Oriole",0.0,0.016129,0.000000,0.000000,0.016129,0.0,0.016129,0.032258,...,0.016129,0.016129,0.000000,0.016129,0.000000,0.000000,0.016129,0.016129,0.000000,0.016129
10,2,Glencairn,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.200000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000
11,2,Hillcrest Village,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,4,Humber Summit,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,1,"Humberlea , Emery",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,2,"Lawrence Manor , Lawrence Heights",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000
15,0,"North Park , Maple Leaf Park , Upwood Park",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.250000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,2,"Northwood Park , York University",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000
17,0,Parkwoods,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,2,Victoria Village,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,3,"Willowdale , Newtonbrook",0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,2,WillowdaleSouth,0.0,0.000000,0.000000,0.034483,0.000000,0.0,0.000000,0.034483,...,0.000000,0.000000,0.000000,0.000000,0.068966,0.000000,0.000000,0.000000,0.034483,0.000000
21,2,WillowdaleWest,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,3,York Mills West,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [49]:
north_york_grouped.set_index('Neighborhood', inplace = True)
north_york_1 = north_york_grouped.loc[: , 'Labels']
north_york_1

Neighborhood
Bathurst Manor , Wilson Heights , Downsview North    2
Bayview Village                                      2
Bedford Park , Lawrence Manor East                   2
Don Mills , Flemingdon Park                          2
Don MillsNorth                                       2
Downsview , CFB Toronto                              3
DownsviewCentral                                     2
DownsviewNorthwest                                   2
DownsviewWest                                        2
Fairview , Henry Farm , Oriole                       2
Glencairn                                            2
Hillcrest Village                                    2
Humber Summit                                        4
Humberlea , Emery                                    1
Lawrence Manor , Lawrence Heights                    2
North Park , Maple Leaf Park , Upwood Park           0
Northwood Park , York University                     2
Parkwoods                                            0
Victoria Village                                     2
Willowdale , Newtonbrook                             3
WillowdaleSouth                                      2
WillowdaleWest                                       2
York Mills West                                      3
Name: Labels, dtype: int32

In [52]:
north_york_df.reset_index(inplace = True)
north_york_df.set_index('Neighborhood', inplace = True)
north_york_df

,Postal Code,Borough,Latitude,Longitude
Neighborhood,,,,
Hillcrest Village,M2H,North York,43.803762,-79.363452
"Fairview , Henry Farm , Oriole",M2J,North York,43.778517,-79.346556
Bayview Village,M2K,North York,43.786947,-79.385975
"York Mills , Silver Hills",M2L,North York,43.757490,-79.374714
"Willowdale , Newtonbrook",M2M,North York,43.789053,-79.408493
WillowdaleSouth,M2N,North York,43.770120,-79.408493
York Mills West,M2P,North York,43.752758,-79.400049
WillowdaleWest,M2R,North York,43.782736,-79.442259
Parkwoods,M3A,North York,43.753259,-79.329656
Don MillsNorth,M3B,North York,43.745906,-79.352188
"Bathurst Manor , Wilson Heights , Downsview North",M3H,North York,43.754328,-79.442259
"Northwood Park , York University",M3J,North York,43.767980,-79.487262
DownsviewWest,M3L,North York,43.739015,-79.506944
DownsviewCentral,M3M,North York,43.728496,-79.495697
DownsviewNorthwest,M3N,North York,43.761631,-79.520999
Victoria Village,M4A,North York,43.725882,-79.315572
"Bedford Park , Lawrence Manor East",M5M,North York,43.733283,-79.419750
"Lawrence Manor , Lawrence Heights",M6A,North York,43.718518,-79.464763
Glencairn,M6B,North York,43.709577,-79.445073
"North Park , Maple Leaf Park , Upwood Park",M6L,North York,43.713756,-79.490074
Humber Summit,M9L,North York,43.756303,-79.565963
"Humberlea , Emery",M9M,North York,43.724766,-79.532242
"Don Mills , Flemingdon Park",M3C,North York,43.725900,-79.340923
"Downsview , CFB Toronto",M3K,North York,43.737473,-79.464763

##### 3.7) Showing final results

In [61]:
final_df = pd.concat([north_york , north_york_df], axis = 1)
final_df.reset_index(inplace = True)

In [62]:
final_df.drop(23 , axis = 0, inplace = True)

In [63]:
final_df

,Neighborhood,Labels,Postal Code,Borough,Latitude,Longitude
0,"Bathurst Manor , Wilson Heights , Downsview North",2.0,M3H,North York,43.754328,-79.442259
1,Bayview Village,2.0,M2K,North York,43.786947,-79.385975
2,"Bedford Park , Lawrence Manor East",2.0,M5M,North York,43.733283,-79.419750
3,"Don Mills , Flemingdon Park",2.0,M3C,North York,43.725900,-79.340923
4,Don MillsNorth,2.0,M3B,North York,43.745906,-79.352188
5,"Downsview , CFB Toronto",3.0,M3K,North York,43.737473,-79.464763
6,DownsviewCentral,2.0,M3M,North York,43.728496,-79.495697
7,DownsviewNorthwest,2.0,M3N,North York,43.761631,-79.520999
8,DownsviewWest,2.0,M3L,North York,43.739015,-79.506944
9,"Fairview , Henry Farm , Oriole",2.0,M2J,North York,43.778517,-79.346556
10,Glencairn,2.0,M6B,North York,43.709577,-79.445073
11,Hillcrest Village,2.0,M2H,North York,43.803762,-79.363452
12,Humber Summit,4.0,M9L,North York,43.756303,-79.565963
13,"Humberlea , Emery",1.0,M9M,North York,43.724766,-79.532242
14,"Lawrence Manor , Lawrence Heights",2.0,M6A,North York,43.718518,-79.464763
15,"North Park , Maple Leaf Park , Upwood Park",0.0,M6L,North York,43.713756,-79.490074
16,"Northwood Park , York University",2.0,M3J,North York,43.767980,-79.487262
17,Parkwoods,0.0,M3A,North York,43.753259,-79.329656
18,Victoria Village,2.0,M4A,North York,43.725882,-79.315572
19,"Willowdale , Newtonbrook",3.0,M2M,North York,43.789053,-79.408493
20,WillowdaleSouth,2.0,M2N,North York,43.770120,-79.408493
21,WillowdaleWest,2.0,M2R,North York,43.782736,-79.442259
22,York Mills West,3.0,M2P,North York,43.752758,-79.400049